# Site settings
title: Babel
tagline: The compiler for writing next generation JavaScript
description: The compiler for writing next generation JavaScript
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://babeljs.io" # the base hostname & protocol for your site
twitter_username: babeljs
github_username: babel

exclude:
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Makefile
  - Rakefile
  - package.json

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Blog Settings
permalink: /blog/:year/:month/:day/:title
paginate: 1
paginate_path: "/blog/page:num/"

gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jemoji
  - jekyll-sitemap

default_js:
  - "//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"
  - "//cdnjs.cloudflare.com/ajax/libs/lodash.js/4.16.3/lodash.min.js"
  - "//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.13/clipboard.min.js"
  - "https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.js"
  - "/scripts/search.js"
  - "/scripts/clipboard.js"
  - "/scripts/open-in-repl.js"

# Get consistent pagination links with production
timezone: "-0500"
