# Site settings
title: Babel
tagline: The compiler for writing next generation JavaScript
description: The compiler for writing next generation JavaScript
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://babeljs.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: babel
exclude: ["node_modules"]

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Blog Settings
permalink: /blog/:year/:month/:day/:title
paginate: 1

gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jemoji

default_js:
  - "//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"
  - "//cdnjs.cloudflare.com/ajax/libs/lodash.js/4.16.3/lodash.min.js"
  - "//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.13/clipboard.min.js"
  - "https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.js"
  - "/scripts/search.js"
  - "/scripts/clipboard.js"

# Compress HTML
compress_html:
  clippings: all
  comments: all
  # endings: all
  profile: false
  startings: [head, body]
